name: Publish 🐍 📦 to PyPI

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  publish-to-pypi:
    if: github.event_name == 'workflow_dispatch'  # Only allow manual triggers
    name: Publish 🐍 distribution 📦 to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/squall-sql
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: |
          uv sync

      - name: Get version from __init__.py
        id: get_version
        run: |
          version=$(uv run python -c "from src.squall import __version__; print(__version__)")
          echo "Raw version output: $version"
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Check version
        id: check_version
        run: |
          echo "Version in env: ${{ env.VERSION }}"
          if [ -z "${{ env.VERSION }}" ]; then
            echo "Error: VERSION is empty"
            exit 1
          fi

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
